In [3]:
import numpy as np
import pandas as pd
import math

In [4]:
dataset=pd.read_excel('dataset.xlsx')

In [5]:
dataset

Unnamed: 0     Y        X1        X2        X3        X4        X5  \
0         Ar  5.45  4.929955  4.830848  4.810793  4.918248  4.920902   
1         Ca  5.21  4.894739  4.832620  4.833529  4.886971  4.887640   
2         Ch  5.86  4.502968  4.434510  4.391272  4.493071  4.498744   
3         HC  6.14  4.564587  4.497053  4.458420  4.555656  4.560705   
4         Lo  5.28  5.598702  5.529642  5.532023  5.593442  5.593140   
5         Na  6.57  4.796760  4.745032  4.730766  4.788860  4.790739   
6         Re  6.01  5.432366  5.335872  5.317236  5.424403  5.426834   
7         Ri  5.06  5.714682  5.655373  5.651670  5.708763  5.709267   
8         Th  5.07  5.509044  5.433208  5.398526  5.493716  5.498356   

         X6        X7        X8  ...   X20        X21        X22        X23  \
0  4.928513  4.721987  4.909291  ...   930  35.466667  22.212688  29.957125   
1  4.895138  4.764922  4.877566  ...   738  32.250000  21.898052  28.759116   
2  4.498732  4.352381  4.493187  ...   584  25.233333  16.401355  22.375220   
3  4.560705  4.413707  4.555512  ...   600  26.233333  17.108462  23.137669   
4  5.599741  5.442507  5.585346  ...  1298  54.500000  35.240270  47.524121   
5  4.796472  4.690073  4.782528  ...   742  31.150000  20.265059  26.986657   
6  5.430407  5.213292  5.417822  ...  1360  50.245238  31.352112  42.283610   
7  5.715150  5.583846  5.701597  ...  1366  58.450000  38.258967  51.268922   
8  5.813532  5.363974  5.485191  ...  1536  54.900000  33.054648  44.215764   

   X24         X25         X26   X27   X28   X29  
0  392   72.000000  250.765625  0.26  0.86 -0.07  
1  349   71.833333  214.406250  0.28  0.86 -0.16  
2  262   51.666667  181.531250  0.31  0.86  0.13  
3  270   53.666667  189.531250  0.11  0.92  0.02  
4  578  112.000000  378.734375  0.41  0.82 -0.03  
5  339   65.500000  207.656250  0.11  0.89  0.05  
6  586  104.666667  349.607491  0.20  0.89  0.03  
7  622  122.333333  399.328125  0.35  0.85 -0.07  
8  638  109.000000  369.218750  0.34  0.86 -0.04  

[9 rows x 31 columns]

In [6]:
data=dataset.iloc[:,2:]

In [7]:
data['Y']=dataset.iloc[:,1]

In [8]:
#output variable
y=data.iloc[:,-1].values

In [9]:
data

X1        X2        X3        X4        X5        X6        X7  \
0  4.929955  4.830848  4.810793  4.918248  4.920902  4.928513  4.721987   
1  4.894739  4.832620  4.833529  4.886971  4.887640  4.895138  4.764922   
2  4.502968  4.434510  4.391272  4.493071  4.498744  4.498732  4.352381   
3  4.564587  4.497053  4.458420  4.555656  4.560705  4.560705  4.413707   
4  5.598702  5.529642  5.532023  5.593442  5.593140  5.599741  5.442507   
5  4.796760  4.745032  4.730766  4.788860  4.790739  4.796472  4.690073   
6  5.432366  5.335872  5.317236  5.424403  5.426834  5.430407  5.213292   
7  5.714682  5.655373  5.651670  5.708763  5.709267  5.715150  5.583846   
8  5.509044  5.433208  5.398526  5.493716  5.498356  5.813532  5.363974   

         X8        X9       X10  ...        X21        X22        X23  X24  \
0  4.909291  4.950494  4.952164  ...  35.466667  22.212688  29.957125  392   
1  4.877566  4.903741  4.904739  ...  32.250000  21.898052  28.759116  349   
2  4.493187  4.521989  4.522527  ...  25.233333  16.401355  22.375220  262   
3  4.555512  4.583452  4.569594  ...  26.233333  17.108462  23.137669  270   
4  5.585346  5.611939  5.612983  ...  54.500000  35.240270  47.524121  578   
5  4.782528  4.804707  4.805647  ...  31.150000  20.265059  26.986657  339   
6  5.417822  5.454338  5.457075  ...  50.245238  31.352112  42.283610  586   
7  5.701597  5.725270  5.726193  ...  58.450000  38.258967  51.268922  622   
8  5.485191  5.519511  5.521490  ...  54.900000  33.054648  44.215764  638   

          X25         X26   X27   X28   X29     Y  
0   72.000000  250.765625  0.26  0.86 -0.07  5.45  
1   71.833333  214.406250  0.28  0.86 -0.16  5.21  
2   51.666667  181.531250  0.31  0.86  0.13  5.86  
3   53.666667  189.531250  0.11  0.92  0.02  6.14  
4  112.000000  378.734375  0.41  0.82 -0.03  5.28  
5   65.500000  207.656250  0.11  0.89  0.05  6.57  
6  104.666667  349.607491  0.20  0.89  0.03  6.01  
7  122.333333  399.328125  0.35  0.85 -0.07  5.06  
8  109.000000  369.218750  0.34  0.86 -0.04  5.07  

[9 rows x 30 columns]

In [10]:
data.corr()

X1        X2        X3        X4        X5        X6        X7  \
X1   1.000000  0.999405  0.998600  0.999979  0.999990  0.981903  0.996908   
X2   0.999405  1.000000  0.999532  0.999479  0.999447  0.981096  0.998942   
X3   0.998600  0.999532  1.000000  0.998812  0.998664  0.976579  0.998741   
X4   0.999979  0.999479  0.998812  1.000000  0.999993  0.980779  0.996995   
X5   0.999990  0.999447  0.998664  0.999993  1.000000  0.981288  0.996931   
X6   0.981903  0.981096  0.976579  0.980779  0.981288  1.000000  0.981376   
X7   0.996908  0.998942  0.998741  0.996995  0.996931  0.981376  1.000000   
X8   0.999953  0.999483  0.998707  0.999982  0.999987  0.980670  0.996970   
X9   0.999935  0.999009  0.998059  0.999906  0.999934  0.981334  0.996012   
X10  0.999903  0.998925  0.998040  0.999865  0.999885  0.981338  0.995921   
X11  0.999343  0.999657  0.999083  0.999280  0.999266  0.984376  0.998726   
X12  0.999885  0.999116  0.998048  0.999868  0.999909  0.981322  0.996258   
X13  0.893723  0.901525  0.904466  0.894558  0.893999  0.867027  0.909593   
X14  0.994747  0.993390  0.989494  0.994266  0.994660  0.990042  0.990541   
X15  0.981224  0.977557  0.971360  0.980104  0.980795  0.992192  0.973173   
X16  0.974641  0.975954  0.976908  0.975743  0.975504  0.925218  0.972279   
X17  0.987920  0.989315  0.989169  0.988608  0.988511  0.951697  0.987043   
X18  0.994431  0.993149  0.989173  0.993959  0.994360  0.989497  0.990349   
X19  0.984754  0.986333  0.986239  0.985528  0.985419  0.946231  0.984003   
X20  0.956648  0.950284  0.942130  0.954955  0.955906  0.980814  0.943663   
X21  0.993991  0.992759  0.988711  0.993528  0.993934  0.988828  0.989979   
X22  0.995912  0.996921  0.995526  0.996099  0.996170  0.974571  0.995667   
X23  0.994679  0.995262  0.993431  0.994869  0.994987  0.972379  0.993238   
X24  0.981674  0.977888  0.972127  0.980619  0.981264  0.990782  0.973196   
X25  0.998281  0.998154  0.996390  0.998252  0.998385  0.981670  0.995976   
X26  0.988785  0.986167  0.981471  0.988408  0.988880  0.978044  0.980832   
X27  0.603367  0.604512  0.604357  0.602877  0.602941  0.607808  0.606828   
X28 -0.544808 -0.548063 -0.556057 -0.545278 -0.544272 -0.520421 -0.552938   
X29 -0.394152 -0.394928 -0.410700 -0.394051 -0.392315 -0.384527 -0.401339   
Y   -0.606752 -0.605658 -0.606684 -0.605214 -0.605261 -0.634371 -0.609395   

           X8        X9       X10  ...       X21       X22       X23  \
X1   0.999953  0.999935  0.999903  ...  0.993991  0.995912  0.994679   
X2   0.999483  0.999009  0.998925  ...  0.992759  0.996921  0.995262   
X3   0.998707  0.998059  0.998040  ...  0.988711  0.995526  0.993431   
X4   0.999982  0.999906  0.999865  ...  0.993528  0.996099  0.994869   
X5   0.999987  0.999934  0.999885  ...  0.993934  0.996170  0.994987   
X6   0.980670  0.981334  0.981338  ...  0.988828  0.974571  0.972379   
X7   0.996970  0.996012  0.995921  ...  0.989979  0.995667  0.993238   
X8   1.000000  0.999906  0.999835  ...  0.993930  0.996501  0.995383   
X9   0.999906  1.000000  0.999953  ...  0.994326  0.995804  0.994817   
X10  0.999835  0.999953  1.000000  ...  0.994056  0.995421  0.994384   
X11  0.999173  0.998886  0.998895  ...  0.992952  0.995425  0.993500   
X12  0.999918  0.999949  0.999848  ...  0.994897  0.996580  0.995727   
X13  0.894277  0.890899  0.891599  ...  0.878121  0.887116  0.883461   
X14  0.994597  0.995039  0.994871  ...  0.999670  0.992913  0.992972   
X15  0.980358  0.981922  0.981923  ...  0.993155  0.974262  0.974904   
X16  0.976469  0.975162  0.974375  ...  0.964964  0.985827  0.986820   
X17  0.989197  0.988090  0.987479  ...  0.981839  0.996100  0.996452   
X18  0.994328  0.994742  0.994520  ...  0.999925  0.993380  0.993652   
X19  0.986199  0.984980  0.984276  ...  0.978891  0.994394  0.995105   
X20  0.955089  0.957862  0.958111  ...  0.973798  0.943273  0.944345   
X21  0.993930  0.994326  0.994056  ...  1.000000  0.993624  0.994097   
X22  0.996501  0.995804  0.995421  ... 

In [11]:
def ols(x,y):
    n=len(x)
    mean_x=np.mean(x)
    mean_y=np.mean(y)
    numr=np.sum(x*y)-n*mean_x*mean_y  #numerator
    deno=np.sum(x*x)-n*mean_x*mean_x   #denomiantor
    m=numr/deno        #slope
    b=mean_y-m*mean_x   #intercept
    return m,b

In [12]:
def tvalue(x,y):
    n=len(x)
    coffs=[]
    coffs=ols(x,y)
    numr=math.sqrt(np.sum((y-coffs[0]*x-coffs[1])**2)/(n-2))
    mean_x=np.mean(x)
    deno=math.sqrt(np.sum((x-mean_x)**2))
    error=round(numr/deno,3)
    if error==0:
        error=numr/deno
    return coffs[0]/error

In [13]:
tvalues=[]
for i in range(29):
    x=data.iloc[:,i].values
    t=tvalue(x,y)
    print("X",i+1,"tvalue =",t)
    tvalues.append(t)

X 1 tvalue = -2.020860378929975
X 2 tvalue = -2.0145479429308835
X 3 tvalue = -2.0177540927413964
X 4 tvalue = -2.013473920752062
X 5 tvalue = -2.0131870565881234
X 6 tvalue = -2.1728251310865407
X 7 tvalue = -2.034001695866731
X 8 tvalue = -2.0016548281890114
X 9 tvalue = -2.011023306774848
X 10 tvalue = -2.0138112649254283
X 11 tvalue = -2.0652919644771894
X 12 tvalue = -2.0161911277108584
X 13 tvalue = -0.8120259314770487
X 14 tvalue = -1.8746020831741352
X 15 tvalue = -2.268134356740308
X 16 tvalue = -1.9893905388462307
X 17 tvalue = -2.0462351471972773
X 18 tvalue = -1.945718206255228
X 19 tvalue = -1.999213700090779
X 20 tvalue = -1.7841526233501006
X 21 tvalue = -2.012707737001481
X 22 tvalue = -2.0960829296822108
X 23 tvalue = -1.9571496938497186
X 24 tvalue = -1.9801395493656133
X 25 tvalue = -2.00008787729406
X 26 tvalue = -1.768923098952124
X 27 tvalue = -4.333167076317937
X 28 tvalue = 2.8400430298938857
X 29 tvalue = 2.55451734550212


In [14]:
from scipy import stats
dof=7
signft=stats.t.isf(0.025,dof)   #significant t

In [15]:
signft

2.3646242510103

In [16]:
for i in range(len(tvalues)):
      if abs(tvalues[i])>signft:
        print("X",i+1,"is an important feature")

X 27 is an important feature
X 28 is an important feature
X 29 is an important feature


#preprocessing ends

In [17]:
x=data.iloc[:,26:29].values

In [18]:
import statsmodels.api as sm
x=sm.add_constant(x)

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.4)

In [20]:
X_train.shape

(5, 4)

# Vectorized Implementation

In [21]:
x_tnspose=X_train.T
x_tnspose

array([[ 1.  ,  1.  ,  1.  ,  1.  ,  1.  ],
       [ 0.2 ,  0.11,  0.31,  0.41,  0.35],
       [ 0.89,  0.92,  0.86,  0.82,  0.85],
       [ 0.03,  0.02,  0.13, -0.03, -0.07]])

In [22]:
x_tnspose.shape

(4, 5)

# solving AW=B where A=x_transpose.x and B=x_transpose.y

In [23]:
w=np.linalg.solve(x_tnspose.dot(X_train),x_tnspose.dot(Y_train))

In [24]:
w

array([ 30.19401048, -10.68807339, -24.91293765,   3.14547837])

In [25]:
#finding the predictive values
y_pred=X_test.dot(w)

In [26]:
ans=pd.DataFrame({'Actual Y' : Y_test,'Predicted Y' : y_pred})

In [27]:
ans

Actual Y  Predicted Y
0      5.07     5.009120
1      5.45     5.769802
2      6.57     7.003082
3      5.21     5.272947

In [28]:
def calculateR2(y_pred,y):
    numr=np.sum((y-y_pred)**2)
    mean_y=y.mean()
    deno=np.sum((y-mean_y)**2)
    return 1-(numr/deno)

In [29]:
calculateR2(y_pred,Y_test)

0.7865689190099024

# Gradient Descent

In [30]:
def gradientDescent(theta,x,y):
    y_pred=x.dot(theta)
    lr=0.1
    n=x.shape[1]
    m=x.shape[0]
    diff=[]
    for j in range(n):
        col=x[:,j]
        r=np.sum((y_pred-y)*col)
        r*=lr
        r/=m
        diff.append(r)
    diff1=np.array(diff)
    theta=theta-diff1
    return theta

In [31]:
def cost_function(theta,x,y):
    y_pred=x.dot(theta)
    m=x.shape[0]
    sum=np.sum((y_pred-y)**2)
    return sum/(2*m)

In [32]:
theta=np.array([0,0,0,0])

In [33]:
for i in range(5000):
    theta=gradientDescent(theta,X_train,Y_train)
    print(theta,"cost =",cost_function(theta,X_train,Y_train))

[0.567    0.152596 0.493358 0.011046] cost = 10.81937774254367
[1.0302472  0.27656272 0.89665578 0.02042546] cost = 7.251627483159709
[1.40872695 0.37713989 1.22637283 0.02844301] cost = 4.870046516443664
[1.71795052 0.45860846 1.49597309 0.03534755] cost = 3.2802472663106186
[1.97059086 0.524466   1.71645682 0.04134241] cost = 2.2189715230571165
[2.17700191 0.57757009 1.89681135 0.04659373] cost = 1.5104914259745688
[2.34564301 0.6202554  2.04437948 0.05123726] cost = 1.0375066215302289
[2.48342554 0.65442939 2.16516037 0.05538388] cost = 0.7217177842235514
[2.5959962  0.68165048 2.2640554  0.0591242 ] cost = 0.5108592199908816
[2.68796842 0.70319191 2.34506909 0.06253226] cost = 0.3700429809461073
[2.76311143 0.72009396 2.41147317 0.06566853] cost = 0.275980963157028
[2.82450476 0.73320652 2.46594071 0.06858242] cost = 0.21312809095225052
[2.87466439 0.74322398 2.51065561 0.07131431] cost = 0.17110784841777066
[2.91564596 0.75071366 2.54740218 0.07389719] cost = 0.14299379228157272
[

In [34]:
y_pred1=X_test.dot(theta)
check=pd.DataFrame({'Actual': Y_test,'Predicted':y_pred1})
check

Actual  Predicted
0    5.07   5.373065
1    5.45   5.434644
2    6.57   6.137459
3    5.21   5.150793

In [35]:
calculateR2(y_pred1,Y_test)

0.7972009853347093